name: CI/CD Pipeline

on:
  push:
    branches:
      - ariari
  pull_request:
    branches:
      - ariari

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Give Gradle wrapper execute permissions
        run: chmod +x ./gradlew  # gradlew에 실행 권한 부여

      - name: Create application.yml file
        run: |
          cat <<EOT >> src/main/resources/application.yml
          spring:
            jackson:
              time-zone: Asia/Seoul
            application:
              name: ariari
            profiles:
              active: prod
            datasource:
              driver-class-name: org.mariadb.jdbc.Driver
              url: ${MARIADB_URL}
              username: ${MARIADB_USERNAME}
              password: ${MARIADB_PASSWORD}
            mail:
              host: smtp.naver.com
              port: 465
              username: ${MAIL_USERNAME}
              password: ${MAIL_PASSWORD}
              properties:
                mail:
                  smtp:
                    auth: true
                    ssl:
                      enable: true
                      trust: smtp.naver.com
                  debug: true
            jpa:
              database-platform: org.hibernate.dialect.MariaDBDialect
              show-sql: true
              hibernate:
                ddl-auto: update
              properties:
                hibernate:
                  format_sql: true
            data:
              redis:
                host: redis
                port: 6379
            servlet:
              multipart:
                maxFileSize: 10MB
                maxRequestSize: 10MB
          server:
            port: 8282
          
          mybatis:
            mapper-locations: mapper/*.xml
            type-aliases-package: com.ariari.ariari.domain
            configuration:
              map-underscore-to-camel-case: true
          
          jwt:
            secret-key: ${JWT_SECRET_KEY}
            access-expiration-time: 36000000
            refresh-expiration-time: 180000000
          kakao:
            client:
              id: ${KAKAO_CLIENT_ID}
              secret: ${KAKAO_CLIENT_SECRET}
              admin: ${KAKAO_CLIENT_ADMIN}
            redirect-uri: https://ariari.kr/auth/kakao
            login-uri: https://kauth.kakao.com/oauth/authorize
            auth-uri: https://kauth.kakao.com/oauth/token
            kapi-uri: https://kapi.kakao.com/v2/user/me
            unlink-uri: https://kapi.kakao.com/v1/user/unlink
          cloud:
            aws:
              credentials:
                accessKey: ${AWS_ACCESS_KEY}
                secretKey: ${AWS_SECRET_KEY}
              s3:
                bucket: ${AWS_S3_BUCKET}
                cloudfrontdomain: ${AWS_S3_CLOUDFRONTDOMAIN}
              region:
                static: ap-northeast-2
              stack:
                auto: false
          email:
            code:
              characters: ${EMAIL_CODE_CHARACTERS}
              code-length: ${EMAIL_CODE_LENGTH}
              expiration-time: ${EMAIL_CODE_EXPIRATION}

          views-manager:
            expiration-date:
              view-duplicate: ${VIEW_DUPLICATE_DUE}
              view: ${VIEW_DUE}

          school-auth:
            key-name: ${SCHOOL_AUTH_KEY_NAME}
            expiration-time: ${SCHOOL_AUTH_EXPRIATION_TIME}
            code-length: ${SCHOOL_AUTH_CODE_LENGTH}
          
          server-secret:
            host: ${SERVER_ADDRESS}
            port: ${SERVER_PORT}

          sentry:
            dsn: ${SENTRY_DSN}
            environment: production
            release: ariari@${GITHUB_SHA}
            send-default-pii: true
            exception-resolver-order: -2147483647
          
          EOT
        env:
          SERVER_ADDRESS: ${{secrets.SERVER_ADDRESS}}
          SERVER_PORT: ${{secrets.SERVER_PORT}}
          MARIADB_URL: ${{ secrets.MARIADB_URL }}
          MARIADB_USERNAME: ${{ secrets.MARIADB_USERNAME }}
          MARIADB_PASSWORD: ${{ secrets.MARIADB_PASSWORD }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
          KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}
          KAKAO_CLIENT_ADMIN: ${{ secrets.KAKAO_CLIENT_ADMIN }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_S3_CLOUDFRONTDOMAIN : ${{ secrets.AWS_S3_CLOUDFRONTDOMAIN }}
          EMAIL_CODE_CHARACTERS: ${{ secrets.MAIL_CODE_CHARACTERS }}
          EMAIL_CODE_LENGTH: ${{ secrets.MAIL_CODE_LENGTH }}
          EMAIL_CODE_EXPIRATION: ${{ secrets.MAIL_CODE_EXPIRATION }}
          VIEW_DUPLICATE_DUE: ${{ secrets.VIEW_DUPLICATE_DUE }}
          VIEW_DUE: ${{ secrets.VIEW_DUE }}
          SCHOOL_AUTH_KEY_NAME: ${{ secrets.SCHOOL_AUTH_KEY_NAME }}
          SCHOOL_AUTH_EXPRIATION_TIME: ${{ secrets.SCHOOL_AUTH_EXPIRATION_TIME }}
          SCHOOL_AUTH_CODE_LENGTH: ${{ secrets.SCHOOL_AUTH_CODE_LENGTH }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: iuholic83/ariari:latest

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          version: ariari@${{ github.sha }}
          fetch-depth: 0

      - name: Deploy with SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu/ariari.kr
            sudo docker compose pull
            sudo docker compose up -d --build